const fs = require('fs'), vm = require('vm'), assert = require('node:assert/strict');
const s={}; vm.createContext(s); vm.runInContext(fs.readFileSync(__dirname+'/../Sim.js','utf8').replace('.pragma library',''),s);
const now = new Date(2026,8,9,12).getTime();
let pet=s.newState(now-86400000,1,0);pet.lastTick=now;
pet.daily={day:'old',actions:['feed'],streak:20,completedDay:'old'};
pet=s.normalize(pet,now);assert.equal(pet.generation,1);assert.equal(pet.daily.streak,20);
for(const a of ['feed','pet','play']) pet=s.act(pet,a,now).state;
assert.equal(pet.daily.streak,20,'Existing history retained without demanding new streaks');
let reunion=s.advance(pet,now+30*86400000,{});
assert.equal(s.isDead(reunion.state),false);assert.ok(reunion.state.stats.happiness>=80);
assert.equal(reunion.state.sick,false);assert.equal(reunion.state.poops,0);assert.ok(reunion.events.includes('reunion'));
assert.equal(s.advance(reunion.state,now+30*86400000,{}).events.includes('reunion'),false);
let neglected=s.clone(pet);neglected.stats={fullness:0,happiness:0,energy:40,hygiene:0,health:1};neglected.sick=true;
assert.equal(s.isDead(s.advance(neglected,now+3600000,{gentleCare:false}).state),false,'Default never kills');
assert.equal(s.isDead(s.advance(neglected,now+3600000,{gentleCare:false,canDie:true}).state),true,'Explicit legacy challenge remains possible');
let live=s.clone(pet);
for(let i=1;i<=5000;i++) live=s.advance(live,now+i*15000,{}).state;
assert.ok(live.stats.fullness>=45);assert.ok(live.stats.happiness>=55);assert.equal(live.sick,false);
let dead=s.clone(pet);dead.diedAt=now-1;assert.equal(s.isDead(s.advance(dead,now+86400000,{}).state),true,'Never silently revive old creatures');
assert.equal(s.personality({seed:4}),'shy');
const msg={}; vm.createContext(msg); vm.runInContext(fs.readFileSync(__dirname+'/../Messages.js','utf8').replace('.pragma library',''),msg);
assert.equal(msg.ui('sv').feed,'Feed');assert.equal(msg.stageLabel('egg','sv'),'Egg');
console.log('Save migration, gentle live/offline care, reunion, opt-in mortality and English checks passed.');
